---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      - name: unit tests
        run: |
         make test-unit

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3
      - name: Static checks
        run: |
         sudo apt-get install shellcheck
         export PATH=.:$PATH
         make checkbashisms checkstyle
